(ns gamma.webgl.platform.constants)

;; adapted from https://github.com/thi-ng/geom/blob/1f447bc3b9e0841e7719d85a36b946df055c54e0/geom-webgl/src/core.org

(def constants
  {::active-attributes                            0x8b89
  ::active-texture                               0x84e0
  ::active-uniforms                              0x8b86
  ::aliased-line-width-range                     0x846e
  ::aliased-point-size-range                     0x846d
  ::alpha                                        0x1906
  ::alpha-bits                                   0xd55
  ::always                                       0x207
  ::array-buffer                                 0x8892
  ::array-buffer-binding                         0x8894
  ::attached-shaders                             0x8b85
  ::back                                         0x405
  ::blend                                        0xbe2
  ::blend-color                                  0x8005
  ::blend-dst-alpha                              0x80ca
  ::blend-dst-rgb                                0x80c8
  ::blend-equation                               0x8009
  ::blend-equation-alpha                         0x883d
  ::blend-equation-rgb                           0x8009
  ::blend-src-alpha                              0x80cb
  ::blend-src-rgb                                0x80c9
  ::blue-bits                                    0xd54
  ::bool                                         0x8b56
  ::bool-vec2                                    0x8b57
  ::bool-vec3                                    0x8b58
  ::bool-vec4                                    0x8b59
  ::browser-default-webgl                        0x9244
  ::buffer-size                                  0x8764
  ::buffer-usage                                 0x8765
  ::byte                                         0x1400
  ::ccw                                          0x901
  ::clamp-to-edge                                0x812f
  ::color-attachment0                            0x8ce0
  ::color-buffer-bit                             0x4000
  ::color-clear-value                            0xc22
  ::color-writemask                              0xc23
  ::compile-status                               0x8b81
  ::compressed-texture-formats                   0x86a3
  ::constant-alpha                               0x8003
  ::constant-color                               0x8001
  ::context-lost-webgl                           0x9242
  ::cull-face                                    0xb44
  ::cull-face-mode                               0xb45
  ::current-program                              0x8b8d
  ::current-vertex-attrib                        0x8626
  ::cw                                           0x900
  ::decr                                         0x1e03
  ::decr-wrap                                    0x8508
  ::delete-status                                0x8b80
  ::depth-attachment                             0x8d00
  ::depth-bits                                   0xd56
  ::depth-buffer-bit                             0x100
  ::depth-clear-value                            0xb73
  ::depth-component                              0x1902
  ::depth-component16                            0x81a5
  ::depth-func                                   0xb74
  ::depth-range                                  0xb70
  ::depth-stencil                                0x84f9
  ::depth-stencil-attachment                     0x821a
  ::depth-test                                   0xb71
  ::depth-writemask                              0xb72
  ::dither                                       0xbd0
  ::dont-care                                    0x1100
  ::drawing-buffer-height                        0x1e0
  ::drawing-buffer-width                         0x280
  ::dst-alpha                                    0x304
  ::dst-color                                    0x306
  ::dynamic-draw                                 0x88e8
  ::element-array-buffer                         0x8893
  ::element-array-buffer-binding                 0x8895
  ::equal                                        0x202
  ::fastest                                      0x1101
  ::float                                        0x1406
  ::float-mat2                                   0x8b5a
  ::float-mat3                                   0x8b5b
  ::float-mat4                                   0x8b5c
  ::float-vec2                                   0x8b50
  ::float-vec3                                   0x8b51
  ::float-vec4                                   0x8b52
  ::fragment-shader                              0x8b30
  ::framebuffer                                  0x8d40
  ::framebuffer-attachment-object-name           0x8cd1
  ::framebuffer-attachment-object-type           0x8cd0
  ::framebuffer-attachment-texture-cube-map-face 0x8cd3
  ::framebuffer-attachment-texture-level         0x8cd2
  ::framebuffer-binding                          0x8ca6
  ::framebuffer-complete                         0x8cd5
  ::framebuffer-incomplete-attachment            0x8cd6
  ::framebuffer-incomplete-dimensions            0x8cd9
  ::framebuffer-incomplete-missing-attachment    0x8cd7
  ::framebuffer-unsupported                      0x8cdd
  ::front                                        0x404
  ::front-and-back                               0x408
  ::front-face                                   0xb46
  ::func-add                                     0x8006
  ::func-reverse-subtract                        0x800b
  ::func-subtract                                0x800a
  ::generate-mipmap-hint                         0x8192
  ::gequal                                       0x206
  ::greater                                      0x204
  ::green-bits                                   0xd53
  ::high-float                                   0x8df2
  ::high-int                                     0x8df5
  ::incr                                         0x1e02
  ::incr-wrap                                    0x8507
  ::int                                          0x1404
  ::int-vec2                                     0x8b53
  ::int-vec3                                     0x8b54
  ::int-vec4                                     0x8b55
  ::invalid-enum                                 0x500
  ::invalid-framebuffer-operation                0x506
  ::invalid-operation                            0x502
  ::invalid-value                                0x501
  ::invert                                       0x150a
  ::keep                                         0x1e00
  ::lequal                                       0x203
  ::less                                         0x201
  ::line-loop                                    0x2
  ::line-strip                                   0x3
  ::line-width                                   0xb21
  ::linear                                       0x2601
  ::linear-mipmap-linear                         0x2703
  ::linear-mipmap-nearest                        0x2701
  ::lines                                        0x1
  ::link-status                                  0x8b82
  ::low-float                                    0x8df0
  ::low-int                                      0x8df3
  ::luminance                                    0x1909
  ::luminance-alpha                              0x190a
  ::max-combined-texture-image-units             0x8b4d
  ::max-cube-map-texture-size                    0x851c
  ::max-fragment-uniform-vectors                 0x8dfd
  ::max-renderbuffer-size                        0x84e8
  ::max-texture-image-units                      0x8872
  ::max-texture-size                             0xd33
  ::max-varying-vectors                          0x8dfc
  ::max-vertex-attribs                           0x8869
  ::max-vertex-texture-image-units               0x8b4c
  ::max-vertex-uniform-vectors                   0x8dfb
  ::max-viewport-dims                            0xd3a
  ::medium-float                                 0x8df1
  ::medium-int                                   0x8df4
  ::mirrored-repeat                              0x8370
  ::nearest                                      0x2600
  ::nearest-mipmap-linear                        0x2702
  ::nearest-mipmap-nearest                       0x2700
  ::never                                        0x200
  ::nicest                                       0x1102
  ::no-error                                     0x0
  ::none                                         0x0
  ::notequal                                     0x205
  ::one                                          0x1
  ::one-minus-constant-alpha                     0x8004
  ::one-minus-constant-color                     0x8002
  ::one-minus-dst-alpha                          0x305
  ::one-minus-dst-color                          0x307
  ::one-minus-src-alpha                          0x303
  ::one-minus-src-color                          0x301
  ::out-of-memory                                0x505
  ::pack-alignment                               0xd05
  ::points                                       0x0
  ::polygon-offset-factor                        0x8038
  ::polygon-offset-fill                          0x8037
  ::polygon-offset-units                         0x2a00
  ::red-bits                                     0xd52
  ::renderbuffer                                 0x8d41
  ::renderbuffer-alpha-size                      0x8d53
  ::renderbuffer-binding                         0x8ca7
  ::renderbuffer-blue-size                       0x8d52
  ::renderbuffer-depth-size                      0x8d54
  ::renderbuffer-green-size                      0x8d51
  ::renderbuffer-height                          0x8d43
  ::renderbuffer-internal-format                 0x8d44
  ::renderbuffer-red-size                        0x8d50
  ::renderbuffer-stencil-size                    0x8d55
  ::renderbuffer-width                           0x8d42
  ::renderer                                     0x1f01
  ::repeat                                       0x2901
  ::replace                                      0x1e01
  ::rgb                                          0x1907
  ::rgb5-a1                                      0x8057
  ::rgb565                                       0x8d62
  ::rgba                                         0x1908
  ::rgba4                                        0x8056
  ::sample-alpha-to-coverage                     0x809e
  ::sample-buffers                               0x80a8
  ::sample-coverage                              0x80a0
  ::sample-coverage-invert                       0x80ab
  ::sample-coverage-value                        0x80aa
  ::sampler-2d                                   0x8b5e
  ::sampler-cube                                 0x8b60
  ::samples                                      0x80a9
  ::scissor-box                                  0xc10
  ::scissor-test                                 0xc11
  ::shader-type                                  0x8b4f
  ::shading-language-version                     0x8b8c
  ::short                                        0x1402
  ::src-alpha                                    0x302
  ::src-alpha-saturate                           0x308
  ::src-color                                    0x300
  ::static-draw                                  0x88e4
  ::stencil-attachment                           0x8d20
  ::stencil-back-fail                            0x8801
  ::stencil-back-func                            0x8800
  ::stencil-back-pass-depth-fail                 0x8802
  ::stencil-back-pass-depth-pass                 0x8803
  ::stencil-back-ref                             0x8ca3
  ::stencil-back-value-mask                      0x8ca4
  ::stencil-back-writemask                       0x8ca5
  ::stencil-bits                                 0xd57
  ::stencil-buffer-bit                           0x400
  ::stencil-clear-value                          0xb91
  ::stencil-fail                                 0xb94
  ::stencil-func                                 0xb92
  ::stencil-index                                0x1901
  ::stencil-index8                               0x8d48
  ::stencil-pass-depth-fail                      0xb95
  ::stencil-pass-depth-pass                      0xb96
  ::stencil-ref                                  0xb97
  ::stencil-test                                 0xb90
  ::stencil-value-mask                           0xb93
  ::stencil-writemask                            0xb98
  ::stream-draw                                  0x88e0
  ::subpixel-bits                                0xd50
  ::texture                                      0x1702
  ::texture-2d                                   0xde1
  ::texture-binding-2d                           0x8069
  ::texture-binding-cube-map                     0x8514
  ::texture-cube-map                             0x8513
  ::texture-cube-map-negative-x                  0x8516
  ::texture-cube-map-negative-y                  0x8518
  ::texture-cube-map-negative-z                  0x851a
  ::texture-cube-map-positive-x                  0x8515
  ::texture-cube-map-positive-y                  0x8517
  ::texture-cube-map-positive-z                  0x8519
  ::texture-mag-filter                           0x2800
  ::texture-min-filter                           0x2801
  ::texture-wrap-s                               0x2802
  ::texture-wrap-t                               0x2803
  ::texture0                                     0x84c0
  ::texture1                                     0x84c1
  ::texture10                                    0x84ca
  ::texture11                                    0x84cb
  ::texture12                                    0x84cc
  ::texture13                                    0x84cd
  ::texture14                                    0x84ce
  ::texture15                                    0x84cf
  ::texture16                                    0x84d0
  ::texture17                                    0x84d1
  ::texture18                                    0x84d2
  ::texture19                                    0x84d3
  ::texture2                                     0x84c2
  ::texture20                                    0x84d4
  ::texture21                                    0x84d5
  ::texture22                                    0x84d6
  ::texture23                                    0x84d7
  ::texture24                                    0x84d8
  ::texture25                                    0x84d9
  ::texture26                                    0x84da
  ::texture27                                    0x84db
  ::texture28                                    0x84dc
  ::texture29                                    0x84dd
  ::texture3                                     0x84c3
  ::texture30                                    0x84de
  ::texture31                                    0x84df
  ::texture4                                     0x84c4
  ::texture5                                     0x84c5
  ::texture6                                     0x84c6
  ::texture7                                     0x84c7
  ::texture8                                     0x84c8
  ::texture9                                     0x84c9
  ::triangle-fan                                 0x6
  ::triangle-strip                               0x5
  ::triangles                                    0x4
  ::unpack-alignment                             0xcf5
  ::unpack-colorspace-conversion-webgl           0x9243
  ::unpack-flip-y-webgl                          0x9240
  ::unpack-premultiply-alpha-webgl               0x9241
  ::unsigned-byte                                0x1401
  ::unsigned-int                                 0x1405
  ::unsigned-short                               0x1403
  ::unsigned-short-4-4-4-4                       0x8033
  ::unsigned-short-5-5-5-1                       0x8034
  ::unsigned-short-5-6-5                         0x8363
  ::validate-status                              0x8b83
  ::vendor                                       0x1f00
  ::version                                      0x1f02
  ::vertex-attrib-array-buffer-binding           0x889f
  ::vertex-attrib-array-enabled                  0x8622
  ::vertex-attrib-array-normalized               0x886a
  ::vertex-attrib-array-pointer                  0x8645
  ::vertex-attrib-array-size                     0x8623
  ::vertex-attrib-array-stride                   0x8624
  ::vertex-attrib-array-type                     0x8625
  ::vertex-shader                                0x8b31
  ::viewport                                     0xba2
  ::zero                                         0x0
  })